IJE -72 Implement New User and Address Registration With Firestore and Firebase Authentication
fhdamd/jamstack-ecommerce pull request #10
Opened 2022-01-23 23:58 UTC by phillip-laTRN

This branch contains my implementation for new user registration using Firestore and Firebase Authentication, where the user's address and important details are created and stored persistently. This branch also contains the implementation for verifying new users by sending verification links to their nominated emails.

* I have tried using environment variables for configuring firebase, by creating a .env file in the root directory. I have also edited the webpack.config.js file. However, "process" is not recognised by the frontend. Anyone who knows how to fix this would be greatly appreciated. 

It however works fine with I directly write the configuration data into firebase.ts without using environment variables. I have not exposed those data in this push.

2022-01-24 01:02 UTC, fahadahmed requested changes

2022-01-24 01:02 UTC, fahadahmed commented on packages/frontend/src/components/InitialSignup.tsx
> +        <h2 data-testid="signup-heading">Sign up to Infosys Goodies</h2>
can you please remove `data-testid`? We have other methods to test the rendering of the content and this should be used only in special cases. Can we remove this and have our tests use assertions like `findByText` or `getByText` methods.

2022-01-24 05:14 UTC, fhdamd requested changes

2022-01-24 05:14 UTC, fhdamd commented on packages/frontend/src/components/UserSignupForm.tsx
> +const actionCodeSettings = {
can this be a dynamic host address?

2022-01-25 00:07 UTC, phillip-laTRN commented on packages/frontend/src/components/InitialSignup.tsx
> +        <h2 data-testid="signup-heading">Sign up to Infosys Goodies</h2>
@fahadahmed @fhdamd I have already made this change in branch IJE-71. Would I need to make the same changes here?

2022-01-25 00:11 UTC, fhdamd commented on packages/frontend/src/components/UserSignupForm.tsx
> +const actionCodeSettings = {
I think I have another question. Why do we need this host address in code?

2022-01-25 00:17 UTC, phillip-laTRN commented on packages/frontend/src/components/UserSignupForm.tsx
> +const actionCodeSettings = {
We have this host address because after the user clicks on the verification link, they are sent to that particular url that I have included in the actionCodeSettings. This actionCodeSettings is a parameter for the sendVerificationLink method.

2022-01-25 00:17 UTC, phillip-laTRN commented on packages/frontend/src/components/UserSignupForm.tsx
> +const actionCodeSettings = {
I want the user to arrive on the nominated url after clicking on the verification link.

2022-01-25 00:54 UTC, phillip-laTRN commented on packages/frontend/src/components/UserSignupForm.tsx
> +const actionCodeSettings = {
@fahadahmed @fhdamd I have made the url dynamic now. It will work with any url that has been approved by firebase.

2022-01-25 01:48 UTC, phillip-laTRN commented
@fahadahmed @fhdamd I have fixed the conflicts on this branch. Please accept this pull request if all is good.

2022-01-25 02:08 UTC, fhdamd approved these changes

2022-01-25 02:11 UTC, merged