IJE 58/product page,  IJE 64/product listing page with product card component
fhdamd/jamstack-ecommerce pull request #14
Opened 2022-01-28 11:59 UTC by zhuTRN

For the team to review the implementation. This has not been merged with the latest GitHub main branch.

2022-01-28 22:09 UTC, fhdamd requested changes

2022-01-28 22:09 UTC, fhdamd commented on packages/frontend/src/components/Navbar/Navbar.tsx
>      // const [clicked, setclicked] = useState(false);
Can you please remove out any commented out code?

2022-01-28 22:09 UTC, fhdamd commented on packages/frontend/src/data/ProductData.tsx
> +export const ProductData = [
Can you please make this a JSON file and import this into your component accordingly?

2022-01-28 22:09 UTC, fhdamd commented on packages/frontend/src/pages/Product/Product.tsx
> +// const titleStyle = css({
Please remove out commented code.

2022-01-28 22:09 UTC, fhdamd commented on packages/frontend/src/pages/Product/Product.tsx
> +const Button = styled.div`
Should these styles come from a separate file so that they are usable? I can see that Button can be re-used in our project along with other styles for Card etc.

2022-01-28 22:09 UTC, fhdamd commented on packages/frontend/tsconfig.json
> +    "jsx": "react-jsx",
any reason why you needed to tweak the `tsconfig` file? were you having issues with emotion styling?

2022-01-31 07:36 UTC, zhuTRN commented on packages/frontend/src/pages/Product/Product.tsx
> +const Button = styled.div`
Thanks for the comment, I will create a separate file to store styles that are reusable.

2022-01-31 07:37 UTC, zhuTRN commented on packages/frontend/tsconfig.json
> +    "jsx": "react-jsx",
I was following the instructions on the emotion website, perhaps I don't have to tweak it?

2022-01-31 07:37 UTC, zhuTRN commented on packages/frontend/src/pages/Product/Product.tsx
> +// const titleStyle = css({
I will finalise my code, thanks!

2022-01-31 07:38 UTC, zhuTRN commented on packages/frontend/src/components/Navbar/Navbar.tsx
>      // const [clicked, setclicked] = useState(false);
I will finalise my code, thanks!

2022-02-01 00:15 UTC, fhdamd commented on packages/frontend/tsconfig.json
> +    "jsx": "react-jsx",
Yeah emotion is already configured to be used in the app. We don't need this change in the config. Can you please revert this?

2022-02-06 22:15 UTC, fhdamd requested changes
The `yarn.lock` file has not had the merge conflicts resolved. Can you please resolve them otherwise this will not work in CI/CD

2022-02-06 22:15 UTC, fhdamd commented on packages/frontend/yarn.lock
> +<<<<<<< HEAD
It seems that the yarn.lock file conflicts have not been merged in properly. Can we resolve this? Might need to delete the file locally and then do `yarn` again for installing the packages and generating this file properly.

2022-02-06 22:15 UTC, fhdamd commented on packages/frontend/yarn.lock
> +<<<<<<< HEAD
Same here -  this conflict has not been resolved properly.

2022-02-06 22:15 UTC, fhdamd commented on packages/frontend/yarn.lock
> +<<<<<<< HEAD
Same here - this conflict has not been resolved properly.

2022-02-06 22:15 UTC, fhdamd commented on packages/frontend/yarn.lock
> +<<<<<<< HEAD
one more

2022-02-07 12:25 UTC, zhuTRN commented
Hey Fahad, I have recommitted with yarn reinstalled, should I wait for your review on the conflicts or should I resolve the conflicts? Thanks.

2022-02-14 02:50 UTC, fhdamd approved these changes

2022-02-14 02:50 UTC, merged