LJE-80/User Profile Page
fhdamd/jamstack-ecommerce pull request #20
Opened 2022-02-04 15:08 UTC by zhuTRN

2022-02-04 15:09 UTC, zhuTRN commented
Hey Fahad, starting from Low fidelity Implementation they are my commits to the user profile page, please let me know if there is any problems.

2022-02-06 22:26 UTC, fhdamd requested changes

2022-02-06 22:26 UTC, fhdamd commented on packages/frontend/src/components/Navbar/Navbar.tsx
> +    return (
Hi Brian, can you please check your tab size and confirm it is set to 2 in your VS Code settings? Seems like if you make a minor change in your file it seems to auto-format the file according to your tab settings.

2022-02-06 22:26 UTC, fhdamd commented on packages/frontend/src/components/ProductCard.tsx
> +    const listItems = ProductData.map((item: any) =>
We shouldn't have the type of any object or variable as `any`. Can we define the right types for the `item` object?

2022-02-06 22:26 UTC, fhdamd commented on packages/frontend/yarn.lock
> +"@babel/runtime@^7.12.5", "@babel/runtime@^7.13.10", "@babel/runtime@^7.16.7", "@babel/runtime@^7.4.4", "@babel/runtime@^7.5.5", "@babel/runtime@^7.7.2", "@babel/runtime@^7.7.6", "@babel/runtime@^7.8
this is again a corrupted `yarn.lock` file. Please regenerate the file properly.

2022-02-06 22:27 UTC, fhdamd commented
Hi Brian,please review the changes requested and resolve the merge conflicts appropriately.

Thanks and good work.

2022-02-08 22:52 UTC, fhdamd approved these changes

2022-02-08 22:53 UTC, fhdamd commented
Hi Brian can you please resolve the merge conflicts? I have approved your changes.

2022-02-10 03:26 UTC, zhuTRN commented
Hey @fhdamd , I am able to see the whole frontend when I yarn start, but for some reason, the deploy preview just doesn't display anything. It still says SignIn is not defined if you go to the deploy preview.
 Do I just merge it since it is working on the development server?

2022-02-10 04:05 UTC, merged