Ije 71
fhdamd/jamstack-ecommerce pull request #8
Opened 2022-01-21 03:35 UTC by phillip-laTRN

I was actually working on the routing for our application this morning. Found out that @fahadahmed @fhdamd was doing the same. This branch contains the merging of my routing with Fahad's.

2022-01-21 06:07 UTC, fahadahmed requested changes
@phillip-laTRN can you please address the feedback when you get a chance?

2022-01-21 06:07 UTC, fahadahmed commented on packages/frontend/src/components/VerificationMessage.tsx
> +        <h2 data-testid="signup-heading">Sign up to Infosys Goodies</h2>
Would like the tests to be written without the usage of `data-testid`. This leads to dirty components.

2022-01-24 00:05 UTC, phillip-laTRN commented on packages/frontend/src/components/SignupBankQuery.tsx
> -const SignupBankQuery = () => {
I agree that the naming can be ambiguous. The "Query" in "SignupBankQuery" means that this component is querying/asking the user whether they want to proceed to add additional information (bank information, in this case) during their new account registration process. It's not a form as the actual form for filling in this information is in the SignupBank component. 

Is there another name that you suggest for the SignupBankQuery component?

2022-01-24 00:55 UTC, fahadahmed commented on packages/frontend/src/components/SignupBankQuery.tsx
> -const SignupBankQuery = () => {
Maybe then use `SignupBankCheck`.

2022-01-25 00:07 UTC, phillip-laTRN commented
@fahadahmed @fhdamd I have made the requested changes to this branch. Please have a look

2022-01-25 00:13 UTC, fhdamd approved these changes

2022-01-25 00:13 UTC, fhdamd commented
Hi @phillip-laTRN , can you please resolve this merge conflicts?

2022-01-25 03:29 UTC, phillip-laTRN commented
@fahadahmed @fhdamd I have solved the merge conflicts. Please have a look and accept if all is good :)

2022-01-25 03:58 UTC, fhdamd approved these changes

2022-01-25 03:59 UTC, fahadahmed approved these changes

2022-01-25 03:59 UTC, merged