LJE-50 - LJE-61  & LJE-62
fhdamd/jamstack-ecommerce pull request #9
Opened 2022-01-23 08:18 UTC by zhuTRN

Hey Team, I have completed a functional navbar component that contains the e-commerce shop title with the logo. The navbar has 4 buttons to go to the homepage, product listing page, sign in and sign up page. These pages also have the navbar at the top to go to different directories. Please take a look and approve my pull request, Thanks!

2022-01-23 08:22 UTC, fahadahmed requested changes

2022-01-23 08:22 UTC, fahadahmed commented on packages/frontend/src/components/Navbar/Navbar.tsx
> +class Navbar extends Component {
Please convert this to a functional component. Class components are an old way to write React components which will become redundant soon.

2022-01-23 11:10 UTC, zhuTRN commented on packages/frontend/src/components/Navbar/Navbar.tsx
> +class Navbar extends Component {
Hey Fahad, thanks for the review, I have now converted Navbar into a functional component, please let me know if there is any problem.

2022-01-23 11:22 UTC, zhuTRN commented
Hey Fahad, thanks for the review, I have now converted Navbar into a functional component, please let me know if there is any problem.

2022-01-23 23:34 UTC, fahadahmed requested changes

2022-01-23 23:34 UTC, fahadahmed commented on packages/frontend/src/components/Navbar/Navbar.tsx
> +// }
Hi Brian. Can you also remove the commented out code?

2022-01-23 23:34 UTC, fahadahmed commented on packages/frontend/src/components/Navbar/Navbar.tsx
> +    // }
Same here. please remove the commented out code.

2022-01-23 23:34 UTC, fahadahmed commented on packages/frontend/src/components/Navbar/Navbar.tsx
> +// `
please remove the commented out code.

2022-01-23 23:34 UTC, fahadahmed commented on packages/frontend/src/components/Navbar/MenuItems.tsx
> +    // },
please remove the commented out code.

2022-01-23 23:34 UTC, fahadahmed commented on packages/frontend/src/pages/Home/Home.tsx
> +    /* align-items: center; */
please remove the commented out code here as well.

2022-01-23 23:35 UTC, fahadahmed commented
Hi @zhuTRN , thanks for completing the conversion of the navbar component to a functional one. Just a minor change. Can you please remove any commented out code in your PR. We would like to keep the code as clean as possible.

2022-01-24 01:07 UTC, fahadahmed approved these changes

2022-01-24 01:07 UTC, merged